[build]
  command = "npm install --force && npm run build"
  publish = "dist"  # Vite outputs to the `dist` directory by default

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

